In [1]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

## Reading csv

In [2]:
df=pd.read_csv("tel_churn.csv")
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,1,0,0,1,1,...,0,0,1,0,1,0,0,0,0,0
1,1,0,56.95,1889.50,0,0,1,1,0,1,...,0,0,0,1,0,0,1,0,0,0
2,2,0,53.85,108.15,1,0,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0
3,3,0,42.30,1840.75,0,0,1,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,4,0,70.70,151.65,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0

In [3]:
df=df.drop('Unnamed: 0',axis=1)

In [4]:
x=df.drop('Churn',axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,1,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,1,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,0,1,1,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,1,1,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,0,1,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
7028,0,103.20,7362.90,1,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,1
7029,0,29.60,346.45,1,0,0,1,0,1,1,...,0,0,1,0,1,0,0,0,0,0
7030,1,74.40,306.60,0,1,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
7031,0,105.65,6844.50,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1

In [5]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

## Train Test Split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Decision Tree Classifier

In [7]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [8]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [9]:
y_pred=model_dt.predict(x_test)
y_pred

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [10]:
model_dt.score(x_test,y_test)

0.7910447761194029

In [11]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1025
           1       0.64      0.53      0.58       382

    accuracy                           0.79      1407
   macro avg       0.74      0.71      0.72      1407
weighted avg       0.78      0.79      0.78      1407

#### As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datasets.
- Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.
- Hence, moving ahead to call SMOTEENN (UpSampling + ENN)

In [16]:
from imblearn.combine import SMOTEENN

sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x, y)

In [18]:
xr_train,xr_test,yr_train,yr_test=train_test_split(x_resampled, y_resampled,test_size=0.2)

In [19]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [20]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9334470989761092
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       529
           1       0.93      0.95      0.94       643

    accuracy                           0.93      1172
   macro avg       0.93      0.93      0.93      1172
weighted avg       0.93      0.93      0.93      1172

In [21]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[481  48]
 [ 30 613]]

- Now we can see quite better results, i.e., Accuracy: 92 %, and a very good recall, precision & f1 score for minority class.
- Let's try with some other classifier.

### Random Forest Classifier

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [24]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [25]:
y_pred=model_rf.predict(x_test)

In [26]:
model_rf.score(x_test,y_test)

0.8102345415778252

In [27]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.94      0.88      1025
           1       0.74      0.46      0.57       382

    accuracy                           0.81      1407
   macro avg       0.78      0.70      0.72      1407
weighted avg       0.80      0.81      0.79      1407

In [34]:
from imblearn.combine import SMOTEENN

sm = SMOTEENN()
x_resampled1, y_resampled1 = sm.fit_resample(x, y)

In [35]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(x_resampled1, y_resampled1,test_size=0.2)

In [36]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [37]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [38]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [39]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [40]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9468267581475128
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       504
           1       0.94      0.97      0.95       662

    accuracy                           0.95      1166
   macro avg       0.95      0.94      0.95      1166
weighted avg       0.95      0.95      0.95      1166

In [41]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[460  44]
 [ 18 644]]

- With RF Classifier, also I are also able to get quite good results, in fact better than Decision Tree.
- I can now further go ahead and create multiple classifiers to see how the model performance is, but that's not covered here, so you can do i

### Performing PCA

In [42]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [43]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [44]:
model.fit(xr_train_pca,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [48]:
yr_predict_pca = model.predict(xr_test_pca)

In [46]:
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [47]:
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

0.7186963979416809
              precision    recall  f1-score   support

           0       0.71      0.59      0.65       504
           1       0.72      0.81      0.77       662

    accuracy                           0.72      1166
   macro avg       0.72      0.70      0.71      1166
weighted avg       0.72      0.72      0.71      1166

- With PCA, I couldn't see any better results, hence let's finalise the model which was created by RF Classifier, and save the model so that we can use it in a later stage :)

## Pickling the model

In [49]:
import pickle

In [50]:
filename = 'model.sav'

In [51]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [52]:
load_model = pickle.load(open(filename, 'rb'))

In [53]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [54]:
model_score_r1

0.9468267581475128

My final model i.e., RF Classifier with SMOTEENN, is now ready and dumped in model.sav, which I will use and prepare API's so that I can access our model from UI.